[2021-01-22 10:31:32,846] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: low_income_hospitals.Data_Quality_Check_for_Low_Income_table 2021-01-22T15:31:28.774982+00:00 [queued]>
[2021-01-22 10:31:32,857] {taskinstance.py:826} INFO - Dependencies all met for <TaskInstance: low_income_hospitals.Data_Quality_Check_for_Low_Income_table 2021-01-22T15:31:28.774982+00:00 [queued]>
[2021-01-22 10:31:32,857] {taskinstance.py:1017} INFO - 
--------------------------------------------------------------------------------
[2021-01-22 10:31:32,857] {taskinstance.py:1018} INFO - Starting attempt 1 of 1
[2021-01-22 10:31:32,857] {taskinstance.py:1019} INFO - 
--------------------------------------------------------------------------------
[2021-01-22 10:31:32,865] {taskinstance.py:1038} INFO - Executing <Task(DataQualityOperator): Data_Quality_Check_for_Low_Income_table> on 2021-01-22T15:31:28.774982+00:00
[2021-01-22 10:31:32,869] {standard_task_runner.py:51} INFO - Started process 41528 to run task
[2021-01-22 10:31:32,880] {standard_task_runner.py:75} INFO - Running: ['airflow', 'tasks', 'run', 'low_income_hospitals', 'Data_Quality_Check_for_Low_Income_table', '2021-01-22T15:31:28.774982+00:00', '--job-id', '76', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/low_income_hospitals.py', '--cfg-path', '/var/folders/yg/z5092h4j73z95n7zhxq2kwx1szwm14/T/tmp9h633tpa']
[2021-01-22 10:31:32,881] {standard_task_runner.py:76} INFO - Job 76: Subtask Data_Quality_Check_for_Low_Income_table
[2021-01-22 10:31:32,921] {logging_mixin.py:103} INFO - Running <TaskInstance: low_income_hospitals.Data_Quality_Check_for_Low_Income_table 2021-01-22T15:31:28.774982+00:00 [running]> on host shs-l5320.ssp.pri
[2021-01-22 10:31:32,949] {taskinstance.py:1232} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=zawnaingwynn@gmail.com
AIRFLOW_CTX_DAG_OWNER=Harry
AIRFLOW_CTX_DAG_ID=low_income_hospitals
AIRFLOW_CTX_TASK_ID=Data_Quality_Check_for_Low_Income_table
AIRFLOW_CTX_EXECUTION_DATE=2021-01-22T15:31:28.774982+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-01-22T15:31:28.774982+00:00
[2021-01-22 10:31:32,958] {base.py:74} INFO - Using connection to: id: postgres_default. Host: postgres, Port: None, Schema: airflow, Login: postgres, Password: XXXXXXXX, extra: None
[2021-01-22 10:31:32,961] {taskinstance.py:1396} ERROR - could not translate host name "postgres" to address: nodename nor servname provided, or not known
Traceback (most recent call last):
  File "/Users/zwin/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1086, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/Users/zwin/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1260, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/Users/zwin/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1300, in _execute_task
    result = task_copy.execute(context=context)
  File "/Users/zwin/Desktop/airflow/plugins/operators/data_quality.py", line 29, in execute
    records = redshift_hook.run(self.test_query)
  File "/Users/zwin/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 173, in run
    with closing(self.get_conn()) as conn:
  File "/Users/zwin/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/airflow/providers/postgres/hooks/postgres.py", line 108, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/Users/zwin/opt/anaconda3/envs/airflow/lib/python3.7/site-packages/psycopg2/__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "postgres" to address: nodename nor servname provided, or not known

[2021-01-22 10:31:32,968] {taskinstance.py:1440} INFO - Marking task as FAILED. dag_id=low_income_hospitals, task_id=Data_Quality_Check_for_Low_Income_table, execution_date=20210122T153128, start_date=20210122T153132, end_date=20210122T153132
[2021-01-22 10:31:33,018] {local_task_job.py:118} INFO - Task exited with return code 1
